[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/receipts/*"
  to = "/.netlify/functions/receipts/:splat"
  status = 200

[[redirects]]
  from = "/api/receipts"
  to = "/.netlify/functions/receipts"
  status = 200

[[redirects]]
  from = "/r/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200
